name: Create release
run-name: Create release

on:
  push:
    paths:
      - "urls.json"

  workflow_dispatch:
    inputs:
      version:
        description: "Version of the ISO to build. This will be used for the tag and release name."
        required: true

      pre-release:
        description: "Pre-release"
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y mkisofs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Get desired StresKit version to build
        id: get-version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            tag=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | grep -oP '"tag_name": "\K[^"]+')

            IFS='.' read -ra split_version <<< "$tag"

            major="${split_version[0]}"
            minor="${split_version[1]}"

            new_version="$major.$((minor + 1)).0"

            echo "version=$new_version" >> $GITHUB_OUTPUT
          fi

      - name: Build ISO
        run: python3 build.py --image_version ${{ steps.get-version.outputs.version }}

      - name: Calculate SHA256
        run: |
          files=("StresKit-v${{ steps.get-version.outputs.version }}-x86_64.iso")

          for file in "${files[@]}"; do
              hash=$(sha256sum "$file" | awk '{print $1}')
              echo "$file $hash" >> "sha256.txt"
          done

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          name: StresKit v${{ steps.get-version.outputs.version }}
          prerelease: ${{ inputs.pre-release }}
          artifacts: StresKit-v${{ steps.get-version.outputs.version }}-x86_64.iso,sha256.txt
          generateReleaseNotes: true
