name: Update URLs
run-name: Update URLs

on:
  workflow_dispatch:

  # weekly workflow runs
  # schedule:
  #   - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  update_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1

      # runs script to check and update urls.json
      # - name: Check for URL updates
      #   run: python3 <script>

      - name: Update urls.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update URLs
          file_pattern: urls.json
